### ROOT

GET http://localhost:3000/api/v1/ HTTP/1.1
Content-Type: application/json

### AUTHENTICATION

### Register

POST http://localhost:3000/api/v1/register HTTP/1.1
content-type: application/json

{
    "email": "admin@admin.com",
    "password": "password",
    "name": "admin",
    "lastName": "admin"
}

### Login

POST http://localhost:3000/api/v1/login HTTP/1.1
content-type: application/json

{
    "email": "admin@admin.com",
    "password": "password"
}

### Logout

POST http://localhost:3000/api/v1/logout HTTP/1.1
content-type: application/json

###Profile

GET http://localhost:3000/api/v1/profile HTTP/1.1
Content-Type: application/json